name: linkup-dev

services:
  web:
    extends:
      service: web
      file: ./frontend/docker-compose-dev.yaml
    depends_on:
      - api
    image: linkup-dev-web
    container_name: linkup-dev-web
    develop:
      watch:
        # dependencies
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        # app
        - path: ./frontend
          target: /app
          action: sync

  api:
    extends:
      service: api
      file: ./backend/docker-compose-dev.yaml
    depends_on:
      - db
    image: linkup-dev-api
    container_name: linkup-dev-api
    develop:
      watch:
        # dependencies
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        # app
        - path: ./backend
          target: /app
          action: sync

  db:
    extends:
      service: db
      file: ./backend/docker-compose-dev.yaml
    container_name: linkup-dev-db

# volumes
volumes:
  linkup: