name: linkup-backend
services:
  api:
    image: linkup-backend
    container_name: linkup-backend-api
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "9000:9000"
    env_file:
      - .env
    # command: npm run start:docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api"]
      interval: 30s
      timeout: 10s
      retries: 3