name: linkup-backend-dev
services:
  api:
    depends_on: 
    - db
    image: linkup-backend-dev
    container_name: linkup-backend-dev-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    # environment: 
    #   DB_URL: mongodb://db/linkup
    env_file:
      - .env.local
    # command: npm run dev
    develop:
      watch:
        # dependencies
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        # app
        - path: .
          target: /app
          action: sync
  
  db:
    image: mongo:latest
    container_name: linkup-backend-dev-db
    ports:
      # default local mongodb port 27017
      - 27017:27017
    volumes:
      # mount volume "linkup" inside the container at /data/db directory
      - linkup:/data/db

# volumes
volumes:
  linkup:
